### ISSUE TITLE
Put prod in Python 3 (from python 2)

### ISSUE THREAD

**Issue by Bl3f** [Frky/moon#4]

**Comment by Bl3f** [comment]
Issue traceback when `pip install requirements`

```
Exception:
Traceback (most recent call last):
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/tarfile.py", line 1641, in bz2open
    import bz2
  File "/usr/local/lib/python3.4/bz2.py", line 20, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ImportError: No module named '_bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/util.py", line 644, in unpack_file
    untar_file(filename, location)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/site-packages/pip/util.py", line 562, in untar_file
    tar = tarfile.open(filename, mode)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/tarfile.py", line 1566, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/var/www/moon/.venv/moon-p3/lib/python3.4/tarfile.py", line 1643, in bz2open
    raise CompressionError("bz2 module is not available")
tarfile.CompressionError: bz2 module is not available
```

**Comment by Bl3f** [comment]
Fuck that life. I recompile a Python3.5 version on Debian (that's not working ftm). With:

`./configure --enable-shared --prefix=/usr/local LDFLAGS="-Wl,-rpath /usr/local/lib" --with-libs='bzip' --disable-ipv6`

```
export CC=/usr/local/bin/clang
export CXX=/usr/local/bin/clang++
export CFLAGS="-g3 -fsanitize=undefined -DPY_FORMAT_LONG_LONG=ll"
export CXXFLAGS="-g3 -fsanitize=undefined -fno-sanitize=vptr -DPY_FORMAT_LONG_LONG=ll"
```

`make install && makealtinstall`
